### ISSUE TITLE
Architecture independant API

### ISSUE THREAD

**Issue by Skallwar** [andre-richter/qemu-exit#6]
I'm using this crate for riscv64 and x86, but the API is different. Is there a way to have only one API for all archs ?

Maybe a struct ?

**Comment by andre-richter** [comment]
The problem with the x86 approach is that you

1. Can’t have exit success due to the way the qemu side is implemented.
2. You always need two arguments for the ISA exit device, there is now way around it.

Since in all cases it’s only a single function call, is it too inconvenient to work with #[target] in the client code?

**Comment by Skallwar** [comment]
> The problem with the x86 approach is that you
> 
>     1. Can’t have exit success due to the way the qemu side is implemented.
Maybe an other value like 255 will do the trick [see](https://os.phil-opp.com/testing/#success-exit-code)

>     2. You always need two arguments for the ISA exit device, there is now way around it.
On riscv64 also. We could just not use the second argument on architectures which does not required it ?
 
> Since in all cases it’s only a single function call, is it too inconvenient to work with #[target] in the client code?
That not too inconvenient but require a wrapper in order to have one API on the client code. So why not directly do it here ?

**Comment by Skallwar** [comment]
Maybe something like this:
``` rust
pub struct QemuExitHandle {
    pub addr: usize,
    pub succes_code: u64,
    pub failure_code: u64,
}

pub trait QemuExit {
    fn new(addr: usize) -> Self;
    fn exit<T>(&self, code: T) -> !
    where
        T: Into<u64>;
    fn exit_success(&self) -> !;
    fn exit_failure(&self) -> !;
}
```
